from snakemake.utils import validate


configfile: "config/config.yaml"


container: "docker://condaforge/mambaforge:4.10.3-6"


include: "rules/common.smk"
include: "rules/resources.smk"
include: "rules/qc_reads.smk"
include: "rules/counts.smk"


rule report:
    input:
        "results/multiqc/multiqc.html",
        expand("results/counts/{sample}/outs/web_summary.html", sample=SAMPLES),
        expand("results/filter_empty/{sample}/knee_plot.png", sample=SAMPLES),
        expand("results/filter_empty/{sample}/tail_end_plot.png", sample=SAMPLES),
